### ISSUE TITLE
同时拥有公司跟原来Github账号，需要设置局部git-user信息

### ISSUE THREAD

**Issue by JosanSun** [rikumi/yzx-webservice#1]
你没有发现，你现在更新你的Github，首页显示不了你的活动记录？原因是你用的公司的git账号。

你可以进入这个库，
然后使用
git config user.email   [你原来的github注册邮箱]               【注意没有--global全局选项】
[可选]git config user.name [**]

这样就能同时使用两个账号进行开发。

**Comment by rikumi** [comment]
我知道啊，这只是帮别人做的小项目，懒得改
